title: Aura
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:

        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS

          fields:
            publishing:
              type: section
              title: PLUGIN_ADMIN.PUBLISHING
              underline: true

              fields:
                header.metadata:
                  unset@: true

        aura:
          type: tab
          title: Aura

          fields:

            header.aura.author:
              type: select
              label: Author
              size: medium
              data-options@: '\Grav\Plugin\AuraAuthorsPlugin::listAuthors'
              options:
                '': ''
